#!/bin/bash

echo "🚀 MLFQ Scheduler Web GUI Demo"
echo "================================"
echo ""
echo "This demo will:"
echo "1. Build the project (if needed)"
echo "2. Show you how to access the Web GUI"
echo "3. Explain the features"
echo ""

# Check if build exists
if [ ! -f "build/mlfq_scheduler" ]; then
    echo "Building project..."
    ./build_web.sh
fi

echo "📋 Quick Start Guide:"
echo ""
echo "1. Run the scheduler:"
echo "   cd build && ./mlfq_scheduler"
echo ""
echo "2. From the menu, select option 5 (Web GUI)"
echo ""
echo "3. Open your browser to: http://localhost:8080"
echo ""
echo "🎨 Web GUI Features:"
echo ""
echo "• Modern Design:"
echo "  - Professional gradient backgrounds"
echo "  - Smooth animations and transitions"
echo "  - Responsive layout for all devices"
echo ""
echo "• Interactive Controls:"
echo "  - Start/Pause/Reset simulation"
echo "  - Step-by-step execution"
echo "  - Adjustable speed (1x-10x)"
echo "  - Add custom processes"
echo ""
echo "• Real-time Visualization:"
echo "  - Color-coded priority queues"
echo "  - Animated process movements"
echo "  - Live performance metrics"
echo "  - Process state tracking"
echo ""
echo "• Professional Features:"
echo "  - Performance dashboard"
echo "  - Process management modal"
echo "  - Hover effects and animations"
echo "  - Mobile-friendly design"
echo ""
echo "🌐 Browser Compatibility:"
echo "  Chrome, Firefox, Safari, Edge (modern versions)"
echo ""
echo "Ready to start? Run: cd build && ./mlfq_scheduler"
